[ ERROR ] Error in file 'F:\Robotframework\sap_testing\Tests\Resource\SE16.robot' on line 3: Library 'SAP_Tcode_Library.py' does not exist.
[ ERROR ] Error in file 'F:\Robotframework\sap_testing\Tests\Resource\SE16.robot' on line 6: Importing library 'ExcelLibrary' failed: ModuleNotFoundError: No module named 'ExcelLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  F:\Robotframework\sap_testing\RoboEnvironment\Symphony\Scripts\robot.exe
  C:\Program Files\Python312\python312.zip
  C:\Program Files\Python312\DLLs
  C:\Program Files\Python312\Lib
  C:\Program Files\Python312
  F:\Robotframework\sap_testing\RoboEnvironment\Symphony
  F:\Robotframework\sap_testing\RoboEnvironment\Symphony\Lib\site-packages
  F:\Robotframework\sap_testing\RoboEnvironment\Symphony\Lib\site-packages\win32
  F:\Robotframework\sap_testing\RoboEnvironment\Symphony\Lib\site-packages\win32\lib
  F:\Robotframework\sap_testing\RoboEnvironment\Symphony\Lib\site-packages\Pythonwin
  F:\Robotframework\sap_testing\RoboEnvironment\Symphony\Lib\site-packages\setuptools\_vendor
  F:\Robotframework\sap_testing
[ ERROR ] Error in file 'F:\Robotframework\sap_testing\Tests\Resource\SE16.robot' on line 7: Library 'Merger.py' does not exist.
[ WARN ] Failed to fetch value for field: Sym.Dev.Heineken_SAP_SERVER
[ WARN ] Traceback (most recent call last):
  File "F:\Robotframework\sap_testing\Execution\Access_Data.py", line 58, in get_data
    field_value = eval(command)
                  ^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
AttributeError: module 'Data.Symphony.Dev' has no attribute 'Heineken_SAP_SERVER'

[ WARN ] Failed to fetch value for field: Sym.Dev.Heineken_SAP_SERVER
[ WARN ] Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 87] The parameter is incorrect

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Robotframework\sap_testing\Execution\Access_Data.py", line 58, in get_data
    field_value = eval(command)
                  ^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
AttributeError: module 'Data.Symphony.Dev' has no attribute 'Heineken_SAP_SERVER'

